apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  containers:
    - name: python
      image: localhost:32000/python-ci:lab
      imagePullPolicy: Always
      command: ["cat"]
      tty: true